Repository wecode-bootcamp-korea/35-1st-magazine-K-frontend, pull requests merged in 2022-07, with the labels that each got.

#5 [35기 주원영] Nav바 2차 리뷰 반영 완료
  public/images/k.png
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
Labels: 완료

#2 [35기 길현민]로그인 회원가입 리펙토링 완료
  .vscode/tasks.json
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
  src/pages/SignUp/signUpInputData.js
Labels: 멘토 리뷰 요청

#7 [35기 길현민]Pay 기능구현 최종본
  public/data/PayProductData.json
  public/images/Close.png
  src/Router.js
  src/assets/images/checkBox.png
  src/pages/Pay/CashComponent.js
  src/pages/Pay/CashComponent.scss
  src/pages/Pay/Pay.js
  src/pages/Pay/Pay.scss
  src/pages/Pay/ProductComponent.js
  src/pages/Pay/ProductComponent.scss
  src/pages/Pay/ProductEditor.js
  src/pages/Pay/ProductEditor.scss
Labels: 멘토 리뷰 요청, 추가 기능 구현 중

#11 [35기 노정은] 상세페이지 리뷰기능 구현 완료, 백엔드와 통신 완료
  src/Router.js
  src/pages/ProductDetail/Comment.js
  src/pages/ProductDetail/Comment.scss
  src/pages/ProductDetail/Detail/Detail.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/Review.js
  src/pages/ProductDetail/Review.scss
Labels: 멘토 리뷰 요청

#13 [35기 길현민]Feature/login 리펙토리 최종본
  src/assets/images/signUpCheckBox.png
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
  src/pages/SignUp/signUpInputData.js
Labels: 멘토 리뷰 요청, 추가 기능 구현 중
